services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch-local
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g           # 메모리 설정 (원하는 대로 조정)
      - xpack.security.enabled=false         # 보안 비활성화(테스트용)
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
     - "9200:9200"  # REST API
     - "9300:9300"  # 클러스터 내부 통신(필요 없으면 제거 가능)

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge